---
## tasks file for deploy_remote
   - name: Set remoteHost
     set_fact:
       remoteHost: "{{ hostvars['vm-ansible-remote']['ansible_host'] }}"

   - name: Set remotePort
     set_fact:
       remotePort: "{{ hostvars['vm-ansible-remote']['ansible_port'] }}"

   - name: create docker context
     shell: docker context create vm-ansible-remote --description "Plone Deployment training" --docker "host=ssh://{{ remoteHost }}:{{ remotePort }}"

  - name: make compose-pull-remote
    shell: make compose-pull-remote
    args:
      chdir: /home/{{ devUser }}/training-deploy-project/ansible/roles/deploy_remote/

  - name: make compose-up-remote
    shell: make compose-up-remote
    args:
      chdir: /home/{{ devUser }}/training-deploy-project/ansible/roles/deploy_remote/