---
  # tasks file for devenv_deploy
  - name: Set up authorized keys for the {{ devUser }} user
    authorized_key: user={{ devUser }} key="{{item}}"
    with_file:
      - /home/{{ devUser }}/.ssh/id_rsa.pub

  - name: Install Curl
    become: yes
    apt:
      name: curl

  - name: Download Node.js v16
    become: yes
    shell: curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    args:
      warn: false

  - name: Install NodeJS, python3-dev, vagrant
    become: yes
    apt:
      name:
        - nodejs
        - python3-dev
        - vagrant
        - apt-transport-https
        - software-properties-common
      update_cache: yes

  - name: Add Docker’s official GPG key
    become: yes
    apt_key:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
      state: present

  - name: Set up the stable repository
    become: yes
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
      state: present

  - name: Update apt and install docker-ce
    become: yes
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Python Packages
    pip:
      name:
        - docker
        - docker-compose
      state: present

  - name: Ensure group docker exists
    become: yes
    ansible.builtin.group:
      name: docker
      state: present

  - name: add user to docker group
    become: yes
    ansible.builtin.user:
      name: "{{ devUser }}"
      groups: docker
      append: yes

  - name: reset ssh connection to allow user changes to affect ansible user
    become: yes
    ansible.builtin.meta:
      reset_connection

  - name: Download VirtualBox
    get_url:
      url: https://download.virtualbox.org/virtualbox/6.1.26/virtualbox-6.1_6.1.26-145957~Debian~buster_amd64.deb 
      dest: /home/{{ devUser }}

  - name: Download libvpx
    get_url:
      url: http://ftp.br.debian.org/debian/pool/main/libv/libvpx/libvpx5_1.7.0-3+deb10u1_amd64.deb
      dest: /home/{{ devUser }}

  - name: Install libvpx
    become: yes
    apt: 
      deb: ./libvpx5_1.7.0-3+deb10u1_amd64.deb
      force: yes
      install_recommends: yes

  - name: Install VirtualBox
    become: yes
    apt: 
      deb: ./virtualbox-6.1_6.1.26-145957~Debian~buster_amd64.deb
      force: yes
      install_recommends: yes

  - name: Load vboxdrv kernal module to make Virtualbox provider
    become: yes
    shell: /sbin/vboxconfig

