---
# tasks file for local
  - name: check if vagrant docker context exits
    shell: docker context inspect vagrant
    register: vagrantexists

  - name: create docker context
    shell: docker context create vagrant --description "Plone Deployment training" --docker "host=ssh://plone@127.0.0.1:2222"
    when: vagrantexists.stdout | length < 0

  - name: make compose-pull-local
    shell: make compose-pull-local
    args:
      chdir: /home/{{ devUser }}/training-deploy-project/ansible/roles/deploy_local/

  - name: make compose-up-local
    shell: make compose-up-local
    args:
      chdir: /home/{{ devUser }}/training-deploy-project/ansible/roles/deploy_local/

